# Generated by Django 5.1.4 on 2024-12-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuta', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
